# Customize these with your info 

title: "mind" 
author: cagatay
description: "a blog"
email: "ctanmail@pm.me"
github: cagta
timezone: Europe/Amsterdam
url: https://cagta.github.io/
language: en_US

# leave these unless you are more familiar with jekyll settings

highlighter: rouge
markdown: kramdown
parse_block_html: false
show_drafts: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      blogpost: true
      layout: post
      og-type: article
      social-media-image: false
    
  -    
    scope:
      path: ""
      type: "pages"
    values:
      layout: page 
      social-media-image: false   

  -    
    scope:
      path: ""
      type: "no-index"
    values:
      layout: page
      no-index: true
      social-media-image: false

collections:
  pages:
    output: true
  no-index:
    output: true
  unlisted:
    output: true

plugins:
  - jekyll-feed

feed:
  posts_limit: 25
  categories:
    - essays
    - notes
    - now
